# Generated by Django 2.0.5 on 2018-06-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllHot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='热点标题')),
                ('url', models.CharField(max_length=32, verbose_name='热点路径')),
                ('source', models.CharField(max_length=32, verbose_name='热点来源')),
                ('content', models.CharField(max_length=32, verbose_name='热点简介')),
                ('img_url', models.CharField(max_length=32, verbose_name='热点图片地址')),
                ('praises', models.IntegerField(default=0, verbose_name='热点获赞数量')),
                ('comments', models.IntegerField(default=0, verbose_name='热点评论数量')),
                ('label', models.IntegerField(choices=[(1, '42区'), (2, '段子'), (3, '图片'), (4, '挨踢1024'), (5, '你问我答')], verbose_name='热点标签')),
                ('storage_time', models.DateTimeField(auto_now_add=True, verbose_name='热点入库时间')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128)),
                ('device', models.CharField(max_length=16, null=True)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.AllHot')),
                ('parent_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc', to='app01.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='TelCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=32, unique=True)),
                ('code', models.CharField(max_length=64)),
                ('times', models.IntegerField(default=0)),
                ('cTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=32, verbose_name='用户昵称')),
                ('telephone', models.CharField(max_length=32, unique=True, verbose_name='用户手机号')),
                ('pwd', models.CharField(max_length=64, verbose_name='用户密码')),
                ('cTime', models.DateTimeField(auto_now_add=True, verbose_name='用户注册时间')),
                ('sex', models.CharField(default=0, max_length=32, verbose_name='用户性别，0为女性，1为男性')),
                ('sign', models.CharField(default='', max_length=32, verbose_name='用户签名文档')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='userinfo',
            index_together={('username', 'pwd')},
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo'),
        ),
        migrations.AddField(
            model_name='allhot',
            name='praise_user',
            field=models.ManyToManyField(to='app01.UserInfo'),
        ),
        migrations.AddField(
            model_name='allhot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to='app01.UserInfo'),
        ),
    ]
